project:
  title: "diapos_curso"

editor: visual

format: 
  revealjs: 
    title-slide-attributes: 
      data-background-image: fondo_ppt_title.png
    center-title-slide: true
    code-link: true
    chalkboard:
      theme: whiteboard
    logo: logos_ine.svg
    incremental: true
    code-overflow: wrap
    slide-number: true
    theme: simple
    css: custom.css

